# -*- coding: utf-8 -*-
"""25febpython

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hbCUE0fUT93qLipVARg3OpurNbDYoiPf
"""

print("hello to the world of python")

print("hello")
#print("world")

"""this is python"""
print("my name is gauri")

x=10
y="gauri"
print(x)
print(y)

#concate
x="gauri"
print("my name is "+x)

x="hello "
y="world"
z=x+y
print(z)

