# -*- coding: utf-8 -*-
"""best50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_qrF7xR87WpLrBpjfEvBJNp5Ho2-nwj
"""

import random
choices =('r','p','s')
cpoints = 0
ppoints = 0

def player():
  global choices
  symbol = input("choose either rock(r),paper(P),scissor(s).").lower()

  if symbol not in choices:
    print("enter the valid")
    return player()
  else:
    return symbol

def computer():
    return random.choice(choices)

def game():
    global cpoints , ppoints
    pchoice = player()
    cchoice= computer()
    print("the compter has choosen ",cchoice)
    print("you choose" , pchoice)

    if pchoice==cchoice:
      print("is a tie")

    elif(pchoice == "r" and cchoice == "s") or (pchoice == "s" and cchoice == "p") or (pchoice == "p" and cchoice == "r"):
      print("you won")
      ppoints=ppoints+1
    else:
      print("i won")
      cpoints=cpoints+1
    print()

print("welcome")
while True:
  for i in  range(5):
    x=game()
    print("your score",ppoints)
    print("my score",cpoints)
    print()
    again = int(input("Press 1 to continue\nPress2 to reset and continue\npress 3 to exit "))
    if again==1: #this is executed if the user wants to play another 5 rounds
      continue
    elif again==2: #this is executed if the user wants to reset the scores and play another 5 rounds
      pPoints=0
      cPoints=0
      continue
    else: #this is executed if the user wants to quit.
      break

print("Ok! Bye!")

pip install qrcode

import qrcode

data = input("enter the data")
version = int(input("enter the version (complecity):"))
box_size=int(input("enter the box sizes"))

qr=qrcode.QRCode(version , box_size , border=2)

qr.add_data(data)

qr.make(fit=True)
img=qr.make_image(fill_color = 'black', black_color='white')

f=input("name it as:")
img.save(f'{f}.png')

print("gnerated")

pip install pyqrcode

import pyqrcode
import png
from PIL import Image

#inserting website name
s = input("Enter your website: ")
print(s)
url = pyqrcode.create(s)

#saving image
img = "qr-code.png"
url.png(img, scale=10)

#opening image
im=Image.open(img)

#show
im