# -*- coding: utf-8 -*-
"""conditionalStatement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18l3bUkxUKSDGOh5KiyNXxGRDF7NYIUkl
"""

#if...statement
a=10
b=5
if a<b:
  print("a is smaller")
else:
  print("b is smaller")

x=input("enter a number")
if x==5:
  print("the value is correct")
else:
  print("the value is incorrect")

#if...elif...else
a=10
# b=20
if a==10:
  print("a is 10")
elif(a==20):
  print("a is 20")
else:
  print("a is 30")