# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eIizdKyqvEBCiVy17_XHXivmXHN_9nZx
"""

#while loop
i=1
while(i<10):
  print(i)
  i=i+1

i=0
while(i<10):
  i=i+1
  if i==5:
    break
  print(i)

i=0
while i<20:
  i=i+1
  if i==10:
    continue
  print(i)

#for loop in python
city=["mumbai","delhi","agra"]
for x in city:
  print(x)

#for loop in python with break 
city=["mumbai","delhi","agra"]
for x in city:
  print(x)
  if x=="mumbai":
    break

#for loop in python with continue
city=["mumbai","delhi","agra"]
for x in city:
  print(x)
  if x=="mumbai":
    continue

#python functions

def add(x,y):
  return x+y

x=10
y=30
add(x,y)

def subtract(y,x):
  return y-x

subtract(30,10)

#function in which taking values from the user
def multiply(x,y):
  return x*y

x=int(input("enter a first number"))
y=int(input("enter the second number"))

multiply(x,y)

#lambda function in python
x=lambda a:a+10
print(x(5))

x=lambda a,b: a+b
print(x(5,4))

x=lambda a,b,c: a+b+c
print(x(4,6,8))