# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7LoLTIGlNsBPh4nkgVQa8X7FW9hA86l
"""

import numpy

import numpy
arr=numpy.array([3,5,7,9,10]) #Once NumPy is installed, import it in your applications by adding the import keyword:
print(arr)

#other way creating alias
import numpy as np
arr=np.array([2,4,6,8,5])
print(arr)

#checking numpy version
import numpy as np
print(np.__version__)