# -*- coding: utf-8 -*-
"""pythoncollection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NfUIm3X6wE-GjRGs78Poy3QoBiyvKLji
"""

# create and print List , tuple , set and dictionary

list1=["apple","mango","banana"]
print(list1)                       #list are mutable

tuple1=("mango", "apple","orange")
print(tuple1)                          #tuples are immutable means can not update

dict1={
    "name":"John",
    "country":"Germany"    #dictionary is in the form of key value pair
}
print(dict1)

set1={"apple","apple","mango"}      #set removes duplicate items
print(set1)