# -*- coding: utf-8 -*-
"""pythonMath.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lfe247KeIJ5vdjuTN99ifUulT4Ovbj0H
"""

x=min(20,30,4)
print(x)

y=max(34,65,88)
print(y)

#finding absolute value
x=abs(-3.45)
print(x)

import math
x=math.pi
print(x)

import math
x=math.ceil(1.4) #round a number upward to its nearest
print(x)

y=math.floor(1.4) #round a number downward to its nearest
print(y)

import math
x=math.sqrt(100)
print(x)

x=pow(5,3)
print(x)